site_name: KSU Guest Lecture
theme: readthedocs
nav:
  - Home: index.md
  - SpatioTemporal Asset Catalog:
    - STAC: stac/stac/index.md
    - Stac-Browser: stac/stac-browser/index.md
  - STAC with Desktop GIS: 
    - QGIS: desktop-gis/qgis/index.md
    - ArcGIS Pro: desktop-gis/arcgis-pro/index.md 
  - Excercise:
    - Palisades: palisades/index.md
  - Resources: 
    - Registry for Open Data on AWS: aws-open-data/index.md
    - Microsoft Planetary Computer: ms-planetary-computer/index.md

